import type { Property } from "./types"

export const initialProperties: Property[] = [
  {
    id: "1",
    nombre: "Casa Moderna en Zona Norte",
    descripcionBreve: "Hermosa casa moderna con acabados de lujo.",
    descripcionLarga: "Hermosa casa moderna con acabados de lujo, amplios espacios y jardin privado. Ubicada en una de las mejores zonas del norte de la ciudad con facil acceso a vias principales.",
    precio: 450000,
    tipo: "house",
    zona: "Norte",
    habitaciones: 4,
    banos: 3,
    areaTotales: 300,
    areaConstruccion: 250,
    antiguedad: "5 anos",
    direccion: "Calle 120 #45-67, Zona Norte",
    imagenes: ["/images/casa-moderna.jpg"],
    caracteristicas: {
      garaje: true,
      piscina: true,
      patio: true,
      seguridadPrivada: true,
      balcon: false,
    },
    estado: "disponible",
    fecha: "2024-01-15",
    latitud: "4.7110",
    longitud: "-74.0721",
  },
  {
    id: "2",
    nombre: "Apartamento Penthouse Centro",
    descripcionBreve: "Espectacular penthouse con vista panoramica.",
    descripcionLarga: "Espectacular penthouse con vista panoramica al centro de la ciudad. Acabados de primera, terraza amplia y zonas comunes de lujo.",
    precio: 380000,
    tipo: "penthouse",
    zona: "Centro",
    habitaciones: 3,
    banos: 2,
    areaTotales: 200,
    areaConstruccion: 180,
    antiguedad: "Nuevo",
    direccion: "Carrera 7 #72-41, Piso 20",
    imagenes: ["/images/apartamento-penthouse.jpg"],
    caracteristicas: {
      garaje: true,
      piscina: false,
      patio: false,
      seguridadPrivada: true,
      balcon: true,
    },
    estado: "disponible",
    fecha: "2024-01-20",
    latitud: "4.6097",
    longitud: "-74.0817",
  },
  {
    id: "3",
    nombre: "Casa Campestre Chapinero",
    descripcionBreve: "Acogedora casa campestre con diseno contemporaneo.",
    descripcionLarga: "Acogedora casa campestre con diseno contemporaneo en zona exclusiva. Amplio jardin, chimenea y zona BBQ perfecta para familias.",
    precio: 520000,
    tipo: "house",
    zona: "Chapinero",
    habitaciones: 5,
    banos: 4,
    areaTotales: 400,
    areaConstruccion: 350,
    antiguedad: "10 anos",
    direccion: "Calle 85 #15-32, Chapinero Alto",
    imagenes: ["/images/casa-campestre.jpg"],
    caracteristicas: {
      garaje: true,
      piscina: false,
      patio: true,
      seguridadPrivada: false,
      balcon: true,
    },
    estado: "vendida",
    fecha: "2024-02-01",
    latitud: "4.6486",
    longitud: "-74.0628",
  },
]

export const zonas = ["Norte", "Centro", "Chapinero", "Sur", "Usaquen", "Suba"]

export const tiposPropiedad: { value: string; label: string }[] = [
  { value: "apartment", label: "Apartamento" },
  { value: "house", label: "Casa" },
  { value: "penthouse", label: "Penthouse" },
  { value: "loft", label: "Loft" },
]
